### ISSUE TITLE
Save previously used wifi credentials

### ISSUE THREAD

**Issue by juliancheal** [particle-iot-archived/spark-core-app-ios#5]
Add ability to save wifi credentials to the app. This would save time when connecting a new/reconnecting a Spark Core to the network. Or in moving from one network to another.

**Comment by towynlin** [comment]
Thanks @juliancheal. I'd love for more discussion to happen on this issue and encourage everyone out there to make comments.  I would tend to avoid saving Wi-Fi credentials in the iOS app because it's a security risk.

The Spark Core saves up to 7 sets of Wi-Fi credentials, so for example, once you connect a Core to your home network and your work network, you won't ever have to set it up again. The Core will seamlessly connect in either place.  The convenience is mostly meant to lie there, inside the Core, but I'm curious to hear more comments from the community.
